DROP DATABASE IF EXISTS Products;
CREATE DATABASE IF NOT EXISTS Products;
USE Products;

CREATE TABLE IF NOT EXISTS Products (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    category VARCHAR(256) NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);
INSERT INTO products (name, category, price) VALUES ('Jarvis', 'AI', 9999.99);
